global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.

# Alertmanager Configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: ['host.docker.internal:9093']


# loading at once and evaluate the rule periodically based on 'evaluation_interval'
# rule_files:
#   - "/alertmanager/alert_rules.yml"

scrape_configs:

- job_name: ES_DEV_ES_Exporter
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - localhost:9114
