version: '3'
#docker-compose -f ./docker-compose.yml up or docker-compose up
name: platform-repository
services:
  
  # default docker instance to run
  # docker run --rm -p 9200:9200 -p 9300:9300 -e "xpack.security.enabled=false" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.8.0
  fn-platform-basic-omni_es:
    image: fn-platform-basic-api:omni_es
    container_name: fn-platform-basic-omni_es
    build:
      context: .
      dockerfile: Dockerfile
      target: omni_es
    ports:
      - 9292:9201
    # restart: unless-stopped
    environment:
      # v_7
      # - node.name=fn-dm-bees-omni-data-01
      # - discovery.type=single-node
      # - http.port=9201
      # - http.cors.enabled=true
      # - http.cors.allow-origin=* 
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      # - http.cors.allow-credentials=true
      # - xpack.security.enabled=false
      # - bootstrap.system_call_filter=false
      # - ES_JAVA_OPTS=-Xms1g -Xmx1g
      
      # v_8
      - http.host=0.0.0.0
      - node.name=fn-dm-bees-omni-data-01
      - node.roles=[data, master]
      - cluster.name=docker-elasticsearch
      - cluster.initial_master_nodes=fn-platform-omni-data-01
      - discovery.seed_hosts=fn-platform-omni-data-01
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - action.destructive_requires_name=false
      - http.port=9201
      - reindex.remote.whitelist=${NODE_WHITE_LIST}
    volumes:
      - data:/usr/share/elasticsearch/data
      # - ./Docker/elasticsearch/backup:/usr/share/elasticsearch/backup
      # - ./Docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9201/_cat/health"]
    networks:
      - bridge
  
  
  fn-platform-basic-kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: fn-platform-basic-omni_es
    ports:
      - 15601:5601
    networks:
      - bridge
    depends_on:
      - fn-platform-basic-omni_es
    environment:
      ELASTICSEARCH_HOSTS: http://fn-platform-basic-omni_es:9201
      
      
volumes:
  data:
    driver: local
    
networks:
  bridge:
    driver: bridge