global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.

# Alertmanager Configuration
alerting:
  alertmanagers:
    - static_configs:
      # docker
      - targets: ['host.docker.internal:9093']
      # Ubuntu Installation manually
      # - targets: ['192.168.64.2:9093']

# loading at once and evaluate the rule periodically based on 'evaluation_interval'
rule_files:
  # - "/alertmanager/alert.rules"
  - "/alertmanager/alert_rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"
  # - 'prometheus.rules.yml'

scrape_configs:

- job_name: "prometheus"
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
    - targets: ["host.docker.internal:9091"]

- job_name: "Postgresql-Exporter"
  static_configs:
    - targets: ["host.docker.internal:9187"]
    
# - job_name: "Django-Basic-Exporter"
#   scrape_interval: 10s
#   metrics_path: "/prometheus/metrics"
#   static_configs:
#     - targets: ["host.docker.internal:9999"]

- job_name: 'redis_exporter_targets'
  static_configs:
    - targets:
      - redis://localhost:6379
      # - redis://host.docker.internal:6379
      # - redis://second-redis-host:6380
      # - redis://second-redis-host:6381
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: host.docker.internal:9121


- job_name: redis_exporter
  static_configs:
    - targets: ["host.docker.internal:9121"]

      
- job_name: node-exporter
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
  - targets: ['host.docker.internal:9100']

- job_name: "Solr-Exporter"
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
    - targets: ["host.docker.internal:9854"]  
  
- job_name: rabbitmq-exporter
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
  - targets: ['host.docker.internal:15692']

- job_name: ES7_BASIC_AUTH_INSTALL_BIN
  basic_auth:
    username: 'elastic'
    password: 'gsaadmin'
  scrape_interval: 10s
  metrics_path: "/_prometheus/metrics"
  static_configs:
  - targets:
    - host.docker.internal:9200
    - host.docker.internal:9210
  
- job_name: ES7_BASIC_AUTH_Elastic_Exporter  
  metrics_path: "/metrics"
  basic_auth:
    username: 'elastic'
    password: 'gsaadmin'
  static_configs:
  - targets: ['host.docker.internal:9115']
  relabel_configs:
  - source_labels: [__address__]
    regex: '(.*)\:9108'
    target_label:  'instance'
    replacement:   '$1'
  - source_labels: [__address__]
    regex:         '.*\.(.*)\.lan.*'
    target_label:  'environment'
    replacement:   '$1'
    
- job_name: Python_Connexion
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
  - targets: ['host.docker.internal:1081']
  
# - job_name: FastAPI
#   scrape_interval: 10s
#   metrics_path: "/metrics"
#   static_configs:
#   - targets: ['host.docker.internal:7000']


- job_name: Kafka_Cluster
  scrape_interval: 10s
  metrics_path: "/metrics"
  static_configs:
  - targets: ['host.docker.internal:9308']


- job_name: python-http-export-local
  scrape_interval: 10s
  static_configs:
  - targets: ['host.docker.internal:9000']

    
