# $ kubectl create namespace my-namespace
# $ kubectl config set-context $(kubectl config current-context) --namespace=my-namespace

# $ kubectl apply -f nginx-deployment.yaml
# $ kubectl get all

# $ minikube ip
# $ curl -s $(minikube ip):30080

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fastapi-basic-label
  name: fastapi-basic-label
  namespace: default
spec:
  containers:
  - name: fastapi-basic-label
    image: fn-fastapi-basic-api:es
    ports:
    - containerPort: 7777
      protocol: TCP