version: '3'
#docker-compose -f ./docker-compose.yml up or docker-compose up
name: cicd-platform
services:
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8089:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - bridge
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      
    
    
networks:
  bridge:
    driver: bridge
      